import { Button } from "@/components/ui/button";
import "../globals.css";
import Link from "next/link";
export const metadata = {
    title: "Next.js",
    description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <div className={"flex min-h-screen"}>
                    <div className={"w-1/4 p-4 bg-slate-500"}>
                        <Link href={"/"}>
                            <Button className="bg-green-500 p-4 rounded-xl">
                                Home
                            </Button>
                        </Link>
                    </div>
                    <div className={"w-[75%]"}>{children}</div>
                </div>
            </body>
        </html>
    );
}